BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE CORREO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CORREOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SOLICITUDES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE SEQUENCE CORREO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE USUARIOS (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE SOLICITUDES (
                             token NUMBER PRIMARY KEY,
                             id_usuario NUMBER NOT NULL,
                             fecha_peticion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             estado VARCHAR2(20) NOT NULL,
                             CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id)
);

CREATE TABLE CORREOS (
                         id NUMBER DEFAULT CORREO_SEQ.NEXTVAL PRIMARY KEY,
                         token VARCHAR2(100) UNIQUE NOT NULL,
                         origen VARCHAR2(50) NOT NULL,
                         destino VARCHAR2(50) NOT NULL,
                         fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         mensaje CLOB NOT NULL,
                         CONSTRAINT fk_origen FOREIGN KEY (origen) REFERENCES USUARIOS(username),
                         CONSTRAINT fk_destino FOREIGN KEY (destino) REFERENCES USUARIOS(username)
);