
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SOLICITUDES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


CREATE TABLE USUARIOS (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE SOLICITUDES (
                             token NUMBER PRIMARY KEY,
                             id_usuario NUMBER NOT NULL,
                             fecha_peticion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             estado VARCHAR2(20) NOT NULL,
                             CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id)
);
