name: Generate Javadoc and Deploy to Pages

on:
  push:
    branches:
      - stable

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate Javadoc
        run: mvn -e generate-sources javadoc:javadoc
        
      - name: List target directory
        run: find target -type d
  
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/reports/apidocs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
